### ISSUE TITLE
Request: Filter/split events by column value

### ISSUE THREAD

**Issue by dadav** [loteoo/icsp#1]
Hey loteoo,

in my usecase I have one big ics file and I'd like to filter certain events and/or save them in separate files. For example:

```bash
# Show me all events with the word "fish" in the summary field
icsp -k summary -f fish foo.ics

# Split the events by summary
icsp -s -k summary -o file_prefix_
```

What do you think?

**Comment by loteoo** [comment]
Hey @dadav! Glad you're finding usecases for your calendar like me! :) 

I think you can achieve what you wanted to do by combining existing unix commands:

Filter by column:
```sh
# Show me all events with the word "fish" in the summary field
icsp -c dtstart,summary,duration foo.ics | awk -F  ',' '$2 ~ /fish/ { print }'
```
That awk command basically mean:
- `-F ','`: use a comma to seperate fields
- If the second field (`$2`) contains the pattern `/fish/`, then print the row

With a little bit of scripting you can achieve your second usecase:
```sh
#!/usr/bin/env bash

icsp -c dtstart,summary,duration foo.ics > foo.csv

all_possible_summary_values=$(cat foo.csv | cut -d ',' -f 2 | uniq)

IFS=$'\n'
for summary in $all_possible_summary_values; do
  cat foo.csv \
    | awk -F  ',' "\$2 ~ /$summary/ { print }" \
    > "file_prefix_${summary}.csv"
done
```

If you have commas in your summaries, use a different delimiter so it plays nicer with the other commands (ex, tab character: $'\t').

In general, following [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Do_One_Thing_and_Do_It_Well), it's better to have icsp just "Do one thing well" so I will not be adding filtering / data manipulation features. It will remain a purely conversion tool :)

**Comment by dadav** [comment]
Ok, thanks for the explaination!! :)
